[package]
name = "whisper-agent"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cpal = "0.15.2"
rubato = "0.12.0"
whisper-rs = "0.5.0"
